# Common Tensor Operations

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

## 3.1 Tensor Transposition
- Transpose of scalar is itself. e.g.: xT = x
- Transpose of vector convers column to row.
- **Scalar and vector transposition** are special cases of **matrix transposition**.
    - Flip of axes over main diagonal such that:  
        ```(X_T)i,j = X_j,i```

In [5]:
# numpy array
X = np.array([[25, 2], [2, 32], [9, 10]])
X

array([[25,  2],
       [ 2, 32],
       [ 9, 10]])

In [4]:
X.T

array([[25,  2,  9],
       [ 2, 32, 10]])

In [11]:
# PyTorch
X_pt = torch.tensor([[25, 2], [2, 32], [9, 10]])
X_pt

tensor([[25,  2],
        [ 2, 32],
        [ 9, 10]])

In [7]:
X_pt.T

tensor([[25,  2,  9],
        [ 2, 32, 10]])

In [14]:
# tensorflow
X_tf = tf.constant([[25, 2], [2, 32], [9, 10]])
print(X_tf)
X_tf = tf.transpose(X_tf)
print(X_tf)

tf.Tensor(
[[25  2]
 [ 2 32]
 [ 9 10]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[25  2  9]
 [ 2 32 10]], shape=(2, 3), dtype=int32)


##3.2 Basic Tensor Arithmetic

### NumPy

In [8]:
X

array([[25,  2],
       [ 2, 32],
       [ 9, 10]])

In [7]:
X+2

array([[27,  4],
       [ 4, 34],
       [11, 12]])

In [6]:
X*2

array([[50,  4],
       [ 4, 64],
       [18, 20]])

In [9]:
X*2 +2

array([[52,  6],
       [ 6, 66],
       [20, 22]])

### PyTorch
- ```torch.add()```
- ```torch.mul(multiplicand, multiplier)```

In [12]:
X_pt + 2 

tensor([[27,  4],
        [ 4, 34],
        [11, 12]])

In [13]:
X_pt * 2

tensor([[50,  4],
        [ 4, 64],
        [18, 20]])

In [14]:
X_pt * 2 + 2

tensor([[52,  6],
        [ 6, 66],
        [20, 22]])

In [15]:
# Alternatively:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [ 6, 66],
        [20, 22]])

### Tensorflow
- ```tf.add()```
- ```tf.multiply(multiplicand, multiplier)```

In [16]:
tf.add(X, 2)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[27,  4],
       [ 4, 34],
       [11, 12]])>

In [17]:
tf.multiply(X,2)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[50,  4],
       [ 4, 64],
       [18, 20]])>

In [18]:
tf.add(tf.multiply(X,2),2)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[52,  6],
       [ 6, 66],
       [20, 22]])>

### Element-wise product
- ```tf.multiply(vector1, vector2)```

------------
If two tensors have the same size, operations are often by default applied element-wise; this is called the Hadamard product or simply the element-wise product.
- ```A⊙X```


In mathematics, the Hadamard product (also known as the element-wise product, entrywise product, or Schur product) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands, where each element i, j is the product of elements i, j of the original two matrices.

------------
Produit matriciel de Hadamard

In [19]:
X

array([[25,  2],
       [ 2, 32],
       [ 9, 10]])

In [21]:
A = X + 2
A

array([[27,  4],
       [ 4, 34],
       [11, 12]])

In [22]:
A + X

array([[52,  6],
       [ 6, 66],
       [20, 22]])

In [23]:
A * X

array([[ 675,    8],
       [   8, 1088],
       [  99,  120]])

In [24]:
A[0][0] * X[0][0]

675

In [25]:
A[1][1] * X[1][1]

1088

In [26]:
A[2][0] * X[2][0]

99

## 3.3 Reduction

Row reduction (or Gaussian elimination) is the process of using row operations to reduce a matrix to row reduced echelon form. This procedure is used to solve systems of linear equations, invert matrices, compute determinants, and do many other things ([Millersville edu](https://sites.millersville.edu/bikenaga/linear-algebra/row-reduction/row-reduction.html)).


Calculating the sum across all elements of a tensor is a common operation. For example: 

* For vector ***x*** of length *n*, we calculate $\sum_{i=1}^{n} x_i$
* For matrix ***X*** with *m* by *n* dimensions, we calculate $\sum_{i=1}^{m} \sum_{j=1}^{n} X_{i,j}$

------------
- torch.sum()
- tf.reduce_sum()
- x.sum(axis=0)

In [30]:
X.sum()

80

In [33]:
torch.sum(X_pt)

tensor(80)

In [41]:
X_tf = tf.constant([[27,  4],
                    [ 4, 34],
                    [11, 12]])

axis0 = tf.reduce_sum(X_tf, 0)
axis1 = tf.reduce_sum(X_tf, 1)

axis0, axis1

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 50], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([31, 38, 23], dtype=int32)>)

In [38]:
X.sum(axis=0)

array([36, 44])

Many other operations can be applied with reduction along all or a selection of axes, e.g.:

- maximum
- minimum
- mean
- product

## 3.4 The Dot Product

- ```np.dot(vector1, vector2, ... vector_n)```
- ```torch.dot(vector1, vector2, ... vector_n)```

If we have two vectors (say, ***x*** and ***y***) with *the same length n*, we can calculate the dot product between them. This is annotated several different ways, including the following: 

* $x \cdot y$
* $x^Ty$
* $\langle x,y \rangle$

Regardless the notation style, the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value.
- $x \cdot y = \sum_{i=1}^{n} x_i y_i$
    - the reductive sum of element-wise products

The dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.

In [43]:
x = np.array([30, 6, 7])
y = np.array([0, 8, 2])

In [44]:
(30 * 0) + (6 * 8) + (7 * 2)

62

### NumPy

In [45]:
np.dot(x, y)

62

### PyTorch

In [51]:
x_pt = torch.tensor(x)
y_pt = torch.tensor(y)

x_pt, y_pt

(tensor([30,  6,  7]), tensor([0, 8, 2]))

In [52]:
torch.dot(x_pt, y_pt)

tensor(62)

### Tensorflow

In [54]:
x_tf = tf.Variable(x)
y_tf = tf.Variable(y)

In [58]:
print(tf.reduce_sum(tf.multiply(x, y)))
tf.reduce_sum(tf.multiply(x_tf, y_tf))

tf.Tensor(62, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=int64, numpy=62>

# Exercises

Key Concepts
- Tensor
    - Scalar
    - Vector
    - Matrix
    - n-tensor
- Transposition
- Norm
- Hadamard product
- Dot product

## 1) Transposition

In [59]:
# yT?
y = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

## 2) Hadamard Product

In [69]:
# Hadamard product?
a = np.array([[25, 10], [-2, 1]])
b = np.array([[-1, 7], [10, 8]])

ab = a * b
ab_tf = tf.multiply(a, b)

ab, ab_tf

(array([[-25,  70],
        [-20,   8]]), <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[-25,  70],
        [-20,   8]])>)

## 3) Dot Product

In [70]:
w = np.array([-1, 2, -2])
x = np.array([5, 10, 0])

dot_np = np.dot(w, x)
dot_pt = torch.dot(torch.tensor(w), torch.tensor(x))

dot_np, dot_pt

(15, tensor(15))