# Matrix Multiplication

- $m[C] = m[A] * n[B]$
- $C_i, _k = \sum_{j} A_i,_jB_j, _k$

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

## 5.1 Matrix-by-Vector Multiplication
- ```np.array A * np.array B```
- ```np.dot(a, b)```
- ```torch.matmul(a, b)```
- ```tf.linalg.matvec(a, b)```

In [ ]:
A = np.array([[3, 4], [5, 6], [7, 8]])
B = np.array([1, 2])

In [ ]:
A * B

array([[ 3,  8],
       [ 5, 12],
       [ 7, 16]])

### NumPy

In [ ]:
ab_np = np.dot(A, B) # even though technically dot products are between vectors only
ab_np

(array([11, 17, 23]), tensor([11, 17, 23]))

### PyTorch

In [ ]:
ab_pt = torch.matmul(torch.tensor(A), torch.tensor(B))
ab_pt

tensor([11, 17, 23])

### Tensorflow

In [ ]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
B_tf = tf.Variable([1, 2])

tf.linalg.matvec(A_tf, B_tf)    # like np.dot(), automatically infers dims in order to perform dot product, matvec, or matrix multiplication

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

## 5.2 Matrix-by-Matrix Multiplication

## NumPy

Note that matrix multiplication is not "commutative" (i.e., $AB \neq BA$) so uncommenting the following line will throw a size mismatch error:

- Error notes: ```dot``` is matrix multiplication, but ```*``` does something else ([StackOverflow](https://stackoverflow.com/questions/24560298/python-numpy-valueerror-operands-could-not-be-broadcast-together-with-shapes)).


In [ ]:
A = np.array([[3, 4], [5, 6], [7, 8]])
B = np.array([[1, 9], [2, 0]])

np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

## PyTorch

In [ ]:
A = torch.tensor(A)
B = torch.tensor(B)

torch.matmul(A, B)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

## 5.3 Symmetric and Identity Matrices

### Symmetric matrix
- (squares shapes only): the values of a square matrix mirror each other about the diagonal. 
- $X^T = X$
- When transpose, **true across the border** (see the snippet below).

In [ ]:
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [ ]:
# Transposition of symmetric matrix

X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
print(B)

B.T == B

tensor([[1, 9],
        [2, 0]])


tensor([[ True, False],
        [False,  True]])

### Identity matrix
- Every element along main diagonal is 1.
- All other elements are 0.
- Notation: $I_n$ where ```n = height (or width)```
- $n-length$ $vector$ unchanged if multiplied by $I_n$.

## NumPy

In [ ]:
I_np = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
a_np = np.array([1, 5, 45])

np.dot(I_np, a_np), np.dot(a_np, I_np)

(array([ 1,  5, 45]), array([ 1,  5, 45]))

## PyTorch

In [ ]:
I  = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [ ]:
# NOT A matrix multiplication
x_pt = torch.tensor([25, 3, 7])
I * x_pt

tensor([[25,  0,  0],
        [ 0,  3,  0],
        [ 0,  0,  7]])

In [ ]:
# Matrix multiplication
torch.matmul(I, x_pt)

tensor([25,  3,  7])

## 5.4 Exercises

### Problem 1: Matrix * Vector

In [39]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b = np.array([-1, 1, -2])

np.dot(a, b)

array([ -3,  -9, -15])

In [32]:
a_pt = torch.tensor(a)
b_pt = torch.tensor(b)

torch.matmul(a_pt, b_pt)

tensor([ -3,  -9, -15])

### Problem 2: Identity matrix

In [41]:
b = np.array([-1, 1, -2])
i = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

np.dot(b, i)

array([-1,  1, -2])

### Problem 3 - Matrix * Matrix

In [43]:
a_tf = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b_tf = tf.Variable([[-1, 1, -2], [0, 1, 2]])

tf.matmul(b_tf, a_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ -9, -11, -13],
       [ 15,  18,  21]], dtype=int32)>

In [44]:
a_pt = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b_pt = torch.tensor([[-1, 1, -2], [0, 1, 2]])

torch.matmul(b_pt, a_pt)

tensor([[ -9, -11, -13],
        [ 15,  18,  21]])

## 5.5 Machine Learning and Deep Learning Applications

### General model  
$y = a + bx_1 + cx_2 + ... + mx_m$  
<br />
- System of linear equations (representing $m-dimensional$ $space$)
$ house prise = location + bed rooms + square mtr + ... + n-th feature$  
$y_1 = a + bx_1,_x1 + cx_1,_2 + ... + mx_1,_m$  
$y_2 = a + bx_2,_x1 + cx_2,_2 + ... + mx_2,_m$  
$y_3 = a + bx_3,_x1 + cx_3,_2 + ... + mx_3,_m$  
...      
$y_n = a + bx_n,_x1 + cx_n,_2 + ... + mx_n,_m$  

For any house $i$ in the dataset, $yi = price$ and $x_i,_1$ to $x_i,_m$ are its features. We solve for parameters $a, b, c$ to $m$.

### Matrix Multiplication in Regression 

- $y's$ are $n cases$ tall.  
$[y_1, y_2, y_3 ...$ $y_n]$  
<br />
- $x's$ are $n features$ wide.  
$[1, x_1,_1 + x_1,_2 + ... + mx_1,_m$ $]$  
$[1, x_2,_1 + x_2,_2 + ... + mx_2,_m$ $]$  
$[1, x_3,_1 + x_3,_2 + ... + mx_3,_m$ $]$  
...  
$[1, x_n,_1 + x_n,_2 + ... + mx_n,_m$ $]$  $multiplied$ $by$ $[a, b, c ... m$ $]$